:Author: K3rnel P4n1k
:Email: losgoomy@gmail.com
:CreationDate: 8 Octobre 2016
:Revision: 1.0
:State: DRAFT
:toc: left
:toc-title: Table des matières

= Traduction du poème _L'ennemi_

== À propos

[format="csv"]
[frame="topbot", grid="none"]
|===
Rédacteur, {Author}
Courriel, {Email}
Version, {Revision}
État, *[red]#{State}#*
|===

== Outils utilisés

[format="csv"]
[options="header"]
[frame="topbot", grid="none"]
|===
Outils    , Liens                                             , Utilisation
AsciiDoc  , http://www.methods.co.nz/asciidoc/                , Rédaction
jbovlaste , http://jbovlaste.lojban.org/                      , Dictionnaire
zmifanva  , http://lojban.lilyx.net/zmifanva/                 , Traducteur
wikibooks , https://en.wikibooks.org/wiki/Lojban/Attitudinals , Attitudinals
git       , https://git-scm.com/                              , Gestion de configuration
|===

== Conventions
=== Présentation des termes
==== Navigation dans le texte source

Il y a quatre strophes, nommées respectivement: §1, §2, §3 & §4;

- Chaque strophe comporte 1 à n lignes annotées des lettres de l'alphabet en
majuscule;
- Si des groupement de lignes non explicites peuvent être utile à l'analyse du
poème alors les lettres de l'alphabet grec seront utilisés pour les désigner;
- Un chevron fermant indique le pendant sémantique dans le texte cible.

.Utilisation de la navigation
[format="csv"]
[options="header"]
[frame="topbot", grid="none"]
|===
Localisateur, Explication
§1 — «lorem ipsum», première occurence de *lorem ipsum* dans la première strophe
§2B — «lorem ipsum», première occurence de *lorem ipsum* dans la deuxième ligne de la deuxième strophe
β — «lorem ipsum», première occurence de *lorem ipsum* dans le set β
§3β, désigne un set β définit explicitement pour la troisième strophe
§δ>, désigne la traduction en lojban du set δ
|===

==== Mise en évidence des sumtis

// Liste des couleurs utilisées pour mettre en valeur les arguments.
:fa: yellow
:fe: lime
:fi: aqua
:fo: blue
:fu: fuchsia

.Attribution d'une couleur aux arguments
[format="csv"]
[options="header"]
[frame="topbot", grid="none"]
|===
Position, designation
x₁, [{fa}]#fa#
x₂, [{fe}]#fe#
x₃, [{fi}]#fi#
x₄, [{fo}]#fo#
x₅, [{fu}]#fu#
|===

== Texte en Français

.Source
[quote, Charles Baudelaire, Les Fleurs du mal]
____
X - L'ennemi

Ma jeunesse ne fut qu'un ténébreux orage, +
Traversé çà et là par de brillants soleils ; +
Le tonnerre et la pluie ont fait un tel ravage, +
Qu'il reste en mon jardin bien peu de fruits vermeils.

Voilà que j'ai touché l'automne des idées, +
Et qu'il faut employer la pelle et les râteaux +
Pour rassembler à neuf les terres inondées, +
Où l'eau creuse des trous grands comme des tombeaux.

Et qui sait si les fleurs nouvelles que je rêve +
Trouveront dans ce sol lavé comme une grève +
Le mystique aliment qui ferait leur vigueur ?

{empty}- O douleur ! ô douleur ! Le Temps mange la vie, +
Et l'obscur Ennemi qui nous ronge le cœur +
Du sang que nous perdons croît et se fortifie !
____

== Décomposition technique
=== Analyse de la première strophe
Cette strophe évoque par le biais d'images
la vie du protagoniste. Ce bilan se décompose en deux parties, α & β,
qui se répondent en écho sur le
même schéma — une grande flaque de noir perlée de quelques tâches de
couleurs — l'une refletant le passé, l'autre le présent.

==== *§1α.* le passé — les ténèbres & la lumière —

****
*§1A.* Ma jeunesse ne fut qu'un ténébreux orage, +
*§1B.* Traversé çà et là par de brillants soleils ;
****

.Présentation des mots pour §1A
[format="csv"]
[options="header"]
[frame="topbot", grid="none"]
|===
Français  , Lojban    , Traduction
jeunesse  , nunci'o   , [{fa}]#fa# is the youth of [{fe}]#fe#
ne fût    , pu        , marque du passé
qu'un     , ??        , ??
ténébreux , manku     , [{fa}]#fa# is dark/lacking in illumination
orage     , lidvilti'a, [{fa}]#fa# is a thunderstorm at place/region [{fe}]#fe#
|===

.Présentation des mots pour §1B
[format="csv"]
[options="header"]
[frame="topbot", grid="none"]
|===
Français    , Lojban    , Traduction
Traversé par, pagre     , [{fa}]#fa# passes through/penetrates barrier/medium/portal [{fe}]#fe# to destination [{fi}]#fi# from origin side [{fo}]#fo#.
çà et là    , .aicu'i   , attidudinal d'indécision
brillants   , gusminra  , [{fa}]#fa# is shiny/gleaming/bright/reflective of light [{fe}]#fe# from source [{fi}]#fi#
soleils     , solri     , [{fa}]#fa# is the sun of home planet [{fe}]#fe# (default Earth) of race [{fi}]#fi#; fa is solar.
|===

On pose *pagre* comme étant le selbri de la proposition.

- §1B — «de brillants soleils ;» devient [{fa}]#fa# ⇒ [{fa}]#lo gusmnira solri ku#
- §1A devient [{fe}]#fe# ⇒ [{fe}]#lo lidvilti'a manku ku cu nunci'o mi#

L'utilisation de *su'u _bridi_ ke* permet de transformer un *bridi* en *selbri*.
En appliquant *lo _selbri_ ku* dessus, alors on transforme le *selbri* en *sumti*.

Ainsi, *lo su'u [{fe}]#§1A># ke ku* devient [{fe}]#fe#.

Soit, après un premier essai: +
⇒ _[{fa}]#lo gusminra solri# [underline]#cu pagre# [{fe}]#lo su'u lo lidvilti'a manku cu nunci'o mi#_

En remplacant l'ordre pour qu'il respecte l'ordre du poème. +
⇒ _[{fe}]#fe lo su'u lo lidvilti'a manku cu nunci'o mi ke# [underline]#cu pagre# [{fa}]#fa lo gusminra solri# vau_

===== Corrections

.Validation sur telegram
[quote, ckule, 14 octobre 2016]
____
IRC/Slack :arrow_heading_down::
*tcarlz*: I think your translation is close +
*tcarlz*: you can get rid of [{fa}]#fa# and [{fe}]#fe# by replacing {pagre} with {se pagre} +
*tcarlz*: {lidvilti'a manku} needs a {lo} in front, and maybe the order of the tanru should be swapped +
____

.Il manque *pu* dans [{fa}]#fa#
WARNING: L'utilistation de *pu* pour marquer la jeunesse passée.

.Il manque *.aicu'i* sur le *selbri*
WARNING: L'utilisationn de *.aicu'i* pour marquer le caractère incertain

.Changement morphologique
TIP: L'utilisation de *se pagre* alterne la valeur de [{fa}]#fa# et de [{fe}]#fe#

****
⇒ _[{fa}]#lo su'u lo lidvilti'a manku cu nunci'o mi ke# [underline]#pu se pagre# .aicu'i [{fe}]#lo gusminra solri#_
****

==== *§1β.* le présent — le climat & les récoltes —
****
*§1C.* Le tonnerre et la pluie ont fait un tel ravage +
*§1D.* Qu'il reste en mon jardin bien peu de fruits vermeils.
****

NOTE: Le mot «ravage» n'existe pas, pour la version anglaise, sur jbovlaste. Pour des raisons pratiques, il sera remplacé par "damage".

.Présentation des mots pour §1C
[format="csv"]
[options="header"]
[frame="topbot", grid="none"]
|===
Français          , Lojban    , Traduction
tonnerre          , lidysina  , [{fa}]#fa# is a sound with emit sound-lightning [{fe}]#fe#
pluie             , carvi     , [{fa}]#fa# rains/showers/[precipitates] to [{fe}]#fe# from [{fi}]#fi#; [{fa}]#fa# is precipitation [not limited to 'rain']
ravage/damage     , tolprali  , [{fa}]#fa# is a damage/harm/loss to [{fe}]#fe# resulting from activity/process [{fi}]#fi#
|===

NOTE: Les mots «reste» et «vermeil» me posent problème. «reste» peux se remplacer par "remain" et «vermeil» par «mûr»/"ripe".

.Présentation des mots pour §1D
[format="csv"]
[options="header"]
[frame="topbot", grid="none"]
|===
Français, Lojban, Traduction
reste/remain, stali   , [{fa}]#fa# remains/stays at/abides/lasts with [{fe}]#fe#
mon         , memimoi , [{fa}]#fa# is mine among [{fe}]#fe# by rule/relationship [{fi}]#fi#; [{fa}]#fa# is my [{fe}]#fe# by rule/relationship [{fi}]#fi#
jardin      , purdi   , [{fa}]#fa# is a garden/tended/cultivated field of family/community/farmer [{fe}]#fe# growing plants/crop [{fi}]#fi#
peu         , sotmei  , [{fa}]#fa# are few
fruit       , grute   , [{fa}]#fa# is a fruit [body-part] of species [{fe}]#fe#
vermeil/mûr , rutma'u , [{fa}]#fa# is ripe in quality [{fe}]#fe#
|===

On pose *tolprali* comme étant le *selbri* de la proposition.

- §1C — «Le tonnerre et la pluie» devient [{fa}]#fa#
- [{fe}]#fe# est sous entendu par §1α, et ne nécessite sans doute pas une mise en valeur explicite
- §1D devient [{fi}]#fi#

TIP: Il doit être possible de placer §1α directement dans [{fe}]#fe#.

Première tentative:

[{fa}]#lo lidysina je carvi ku# [underline]#cu tolprali# [{fe}]#go'i# [{fi}]##
